### ISSUE TITLE
Unable to generate report for vmware ESXi

### ISSUE THREAD

**Issue by bitvijays** [AsBuiltReport/AsBuiltReport.VMware.ESXi#1]
Hello Everyone,

Hope you are doing well. Thank you for creating AsBuiltReport! 

Currently, I am trying to create documentation for VMware ESXi 6.5. I have installed VMware PowerCLI and AsBuiltReport. 

When I am trying to run 

```
New-AsBuiltReport VMware.vSphere -Target IPAddress -Credential (Get-Credential) -Format HTML,Word -OutputPath .
```

I am getting the error 

```
New-AsBuiltReport : Cannot validate argument on parameter 'Id'. The argument is null or empty. Provide an argument
that is not null or empty, and then try the command again.
At line:1 char:1
+ New-AsBuiltReport -Report VMware.vSphere -Target IPAddress -Cred ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,New-AsBuiltReport
```

I can't find the parameter Id in 
```
Get-Help New-AsBuiltReport -full
```

Any suggestions on how to resolve the above would be appreciated.

**Comment by tpcarman** [comment]
Hi @bitvijays,
Unfortunately I have not had any time to work on the VMware ESXi report. At the moment it is not a priority for me, however if you are interested in contributing to this report I would be happy to share the code I have so far. Please be aware that the code is not in working order at the moment and will require effort to get it working.
Cheers,
Tim

**Comment by vlstang50** [comment]
I am also getting the same error, however I am running my report against a vcenter 7 server.  Any way to fix this?
